INSERT INTO test_results (id, name, email, responses, created_at, confirmation) VALUES 
('88c6f9e260', 'Josef', 'josef@gmail.com', '[{"question_id": "a3", "response": false}, {"question_id": "c2", "response": true}, {"question_id": "a8", "response": true}, {"question_id": "c8", "response": true}, {"question_id": "a4", "response": false}, {"question_id": "c9", "response": true}, {"question_id": "b1", "response": false}, {"question_id": "a5", "response": false}, {"question_id": "c10", "response": false}, {"question_id": "a2", "response": true}]', 'DATE()', true),
('da7bc795d6', 'Huston', 'huston@gmail.com', '[{"question_id": "b5", "response": true}, {"question_id": "c4", "response": true}, {"question_id": "b10", "response": false}, {"question_id": "a2", "response": true}, {"question_id": "c10", "response": true}, {"question_id": "c2", "response": true}, {"question_id": "a8", "response": true}, {"question_id": "a10", "response": false}, {"question_id": "c2", "response": true}, {"question_id": "a2", "response": false}]', 'DATE()', true),
('a86388e7bb', 'James', 'james@gmail.com', '[{"question_id": "c8", "response": false}, {"question_id": "a9", "response": true}, {"question_id": "c9", "response": false}, {"question_id": "a10", "response": true}, {"question_id": "c2", "response": true}, {"question_id": "c5", "response": true}, {"question_id": "b2", "response": true}, {"question_id": "c5", "response": false}, {"question_id": "a9", "response": false}, {"question_id": "b10", "response": true}]', 'DATE()', false),
('c092b82980', 'Mark', 'mark@gmail.com', '[{"question_id": "c10", "response": true}, {"question_id": "c1", "response": true}, {"question_id": "c2", "response": true}, {"question_id": "c6", "response": true}, {"question_id": "a8", "response": false}, {"question_id": "c9", "response": false}, {"question_id": "a6", "response": true}, {"question_id": "c7", "response": true}, {"question_id": "b10", "response": false}, {"question_id": "b2", "response": true}]', 'DATE()', true),
('5a473d981b', 'Steven', 'steven@gmail.com', '[{"question_id": "a1", "response": true}, {"question_id": "a5", "response": true}, {"question_id": "c4", "response": false}, {"question_id": "a10", "response": false}, {"question_id": "b8", "response": true}, {"question_id": "b6", "response": false}, {"question_id": "a9", "response": true}, {"question_id": "c10", "response": false}, {"question_id": "c10", "response": false}, {"question_id": "b4", "response": true}]', 'DATE()', false),
('9c4563e23d', 'John', 'john@gmail.com', '[{"question_id": "b2", "response": true}, {"question_id": "a10", "response": false}, {"question_id": "c10", "response": false}, {"question_id": "b10", "response": false}, {"question_id": "a8", "response": true}, {"question_id": "c8", "response": false}, {"question_id": "b9", "response": true}, {"question_id": "c1", "response": false}, {"question_id": "c5", "response": false}, {"question_id": "c1", "response": true}]', 'DATE()', true),
('97257f212e', 'Jessie', 'jessie@gmail.com', '[{"question_id": "a6", "response": true}, {"question_id": "c8", "response": true}, {"question_id": "c3", "response": true}, {"question_id": "c8", "response": true}, {"question_id": "c1", "response": true}, {"question_id": "a10", "response": false}, {"question_id": "c7", "response": false}, {"question_id": "c2", "response": false}, {"question_id": "b10", "response": false}, {"question_id": "c9", "response": true}]', 'DATE()', false),
('f1096b12b2', 'John', 'john@gmail.com', '[{"question_id": "a8", "response": false}, {"question_id": "b1", "response": false}, {"question_id": "a1", "response": false}, {"question_id": "a9", "response": false}, {"question_id": "c5", "response": true}, {"question_id": "b4", "response": false}, {"question_id": "a3", "response": false}, {"question_id": "c1", "response": false}, {"question_id": "a10", "response": true}, {"question_id": "b2", "response": true}]', 'DATE()', false),
('bff9ced9db', 'John', 'john@gmail.com', '[{"question_id": "b3", "response": true}, {"question_id": "a3", "response": true}, {"question_id": "c4", "response": false}, {"question_id": "c2", "response": true}, {"question_id": "b1", "response": true}, {"question_id": "b3", "response": true}, {"question_id": "c1", "response": true}, {"question_id": "c4", "response": false}, {"question_id": "c10", "response": false}, {"question_id": "c10", "response": true}]', 'DATE()', false),
('00c1648c7d', 'Huston', 'huston@gmail.com', '[{"question_id": "a3", "response": true}, {"question_id": "b9", "response": false}, {"question_id": "a1", "response": true}, {"question_id": "a4", "response": false}, {"question_id": "b4", "response": false}, {"question_id": "a2", "response": false}, {"question_id": "c10", "response": false}, {"question_id": "c6", "response": false}, {"question_id": "c10", "response": false}, {"question_id": "b6", "response": true}]', 'DATE()', true);
